# Generated by Django 4.2.1 on 2023-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_level_1', models.CharField(max_length=50)),
                ('level_1', models.CharField(max_length=50)),
                ('id_level_2', models.CharField(max_length=50)),
                ('level_2', models.CharField(max_length=50)),
                ('id_level_3', models.CharField(max_length=50)),
                ('level_3', models.CharField(max_length=50)),
                ('descr_level_1', models.CharField(max_length=300)),
                ('descr_level_2', models.CharField(max_length=300)),
                ('descr_level_3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Id', models.CharField(max_length=20)),
                ('Group_Id', models.CharField(max_length=20)),
                ('User_Id', models.CharField(max_length=20)),
                ('level_2', models.CharField(max_length=50)),
                ('level_3', models.CharField(max_length=50)),
                ('Activity_type', models.CharField(max_length=50)),
                ('Activity_date', models.DateField()),
                ('Activity_start', models.DateTimeField()),
                ('Activity_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Id', models.CharField(max_length=50)),
                ('level_1', models.CharField(max_length=50)),
                ('level_2', models.CharField(max_length=50)),
                ('level_3', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=100)),
                ('Neighborhood', models.CharField(max_length=100)),
                ('Schedule_active', models.CharField(max_length=100)),
                ('Schedule_closed', models.CharField(max_length=100)),
                ('Schedule_plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=50)),
                ('Group_Id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=50)),
                ('Registration_date', models.DateTimeField()),
                ('Sex', models.CharField(max_length=10)),
                ('Birth_date', models.DateField()),
                ('Residence_adress', models.CharField(max_length=500)),
            ],
        ),
    ]
