# Generated by Django 4.2.1 on 2023-05-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groupe',
            new_name='Group',
        ),
    ]
