# Generated by Django 4.2.1 on 2023-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_groupe_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Id', models.CharField(max_length=50)),
                ('level_1', models.CharField(max_length=50)),
                ('level_2', models.CharField(max_length=50)),
                ('level_3', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=100)),
                ('Neighborhood', models.CharField(max_length=100)),
                ('Schedule_active', models.CharField(max_length=100)),
                ('Schedule_closed', models.CharField(max_length=100)),
                ('Schedule_plan', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups_Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Id', models.CharField(max_length=50)),
                ('level_1', models.CharField(max_length=50)),
                ('level_2', models.CharField(max_length=50)),
                ('level_3', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=100)),
                ('Neighborhood', models.CharField(max_length=100)),
                ('Schedule_active', models.CharField(max_length=100)),
                ('Schedule_plan', models.CharField(max_length=100)),
                ('Exp_date', models.DateField()),
                ('Exp_date2', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Attend',
            new_name='Attends',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
