# Generated by Django 4.2.1 on 2023-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_groups_now_exp_date2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups_NowImport',
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Adress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='District',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Group_Id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Neighborhood',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Schedule_active',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='Schedule_plan',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='level_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='level_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups_now',
            name='level_3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
