# Generated by Django 4.2.1 on 2023-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_attends_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Schedule_plan',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
