# Generated by Django 4.2.1 on 2023-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_alter_groups_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Schedule_active',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Schedule_closed',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
