# Generated by Django 4.2.1 on 2023-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_alter_groups_schedule_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Adress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='District',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Neighborhood',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
