# Generated by Django 4.2.1 on 2023-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_alter_groups_adress_alter_groups_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Adress',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='District',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Group_Id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Neighborhood',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Schedule_active',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Schedule_closed',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='Schedule_plan',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='level_1',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='level_2',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='level_3',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
