# Generated by Django 4.2.1 on 2023-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_alter_groups_adress_alter_groups_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attends',
            name='Class_Id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attends',
            name='Group_Id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attends',
            name='User_Id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
